version: '{build}'

image: Visual Studio 2019

pull_requests:  
  do_not_increment_build_number: true

branches:
  only:
    - master

nuget:  
  disable_publish_on_pr: true
  
build_script:
  - cmd: .\psake.bat ci
  
test: off  

artifacts:  
  - path: .\artifacts\**\*.nupkg
    name: NuGet
    
cache:
  - '%APPVEYOR_BUILD_FOLDER%\dotnet-sdk.exe'
  
deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: 30KN4qmkCGCJfgASQdhJtWf4BjY9GM7dGuGRi9gQRnJreQPiXFzvreBHYwPjQ4YN
    on:
      branch: master
      appveyor_repo_tag: true